### ISSUE TITLE
some browsers can't recognize woff font

### ISSUE THREAD

**Issue by ceau** [quasarframework/quasar-cli#10]
how to configure multi font format, there's only one font format now. some browsers can't recognize woff font, this cause showing text instead of icon

**Comment by rstoenescu** [comment]
http://caniuse.com/#search=woff -> all browsers except Opera mini support it.
It may be that you have the icon font installed locally. There's been some issues with that that are fixed for next Quasar (v0.11 not yet released). And if you're building only websites you'll be able to use the CDN if you want.
