### ISSUE TITLE
Filepaths relative to project root in service-worker.js on windows

### ISSUE THREAD

**Issue by mardom1** [quasarframework/quasar-cli#100]
### Software version

OS: Windows 10 Home
Node: v8.9.4
NPM: 5.6.0
Quasar CLI: 0.15.12

### What did you get as the error?

When building my pwa, the filepaths of the cached files are relative to the project root:

```javascript
// service-worker.js (beginning)
"use strict";var precacheConfig=[["dist/pwa-mat/app.143ea1a3b08967962553831af65d4ef0.css","735dafbf5d0dfbe0772fdfba905c88bb"],["dist/pwa-mat/fonts/MaterialIcons-Regular.012cf6a.woff","012cf6a10129e2275d79d6adac7f3b02"],
```

### What were you expecting?

I would expect the dist path to be stripped:

```javascript
// service-worker.js (beginning)
"use strict";var precacheConfig=[["app.143ea1a3b08967962553831af65d4ef0.css","735dafbf5d0dfbe0772fdfba905c88bb"],["fonts/MaterialIcons-Regular.012cf6a.woff","012cf6a10129e2275d79d6adac7f3b02"],
```

### What steps did you take, to get the error?

Just building quasar app in pwa mode.

### Own debugging results

After some digging I found the reason the build path is not stripped.

When looking into the quasar-cli source code I found the place where the SWPrecacheWebpackPlugin is added:

```javascript
// quasar-cli/lib/build/webpack-config.js
new SWPrecacheWebpackPlugin({
  cacheId: cfg.pwa.cacheId,
  filename: cfg.pwa.filename,
  staticFileGlobs: [`${cfg.build.distDir}/**/*.{${cfg.pwa.cacheExt}}`],
  minify: cfg.build.minify,
  stripPrefix: cfg.build.distDir + '/'
}),
```

Logging the stripPrefix option, printed `dist\pwa-mat/` as the strip prefix. As the filepaths only use the forward slash as a separator, the prefix doesn't get stripped.

The backslash comes from `cfg.build.distDir` which is set using `path.join` which on windows uses the backslash as a separator.

Hope this helps fixing the issue.

**Comment by rstoenescu** [comment]
Fix available in CLI v0.15.13 (next version). Thanks for opening this ticket!
