### ISSUE TITLE
`Cannot find module` error after running `quasar mode -a electron`

### ISSUE THREAD

**Issue by cpxPratik** [quasarframework/quasar-cli#103]
### Software version

OS: Ubuntu 16.04
Node:8.11.0
NPM:5.6.0
Any other software related to your bug: Quasar cli: 0.15.14

### What did you get as the error?
`Cannot find module 'autoprefixer'` when running `quasar dev` or `quasar dev -m electron -t mat`

### What were you expecting?
Should have run dev-server.
### What steps did you take, to get the error?
In terminal,
`quasar init quasar-sample ` with 
`yarn install`
`quasar dev`
`quasar mode -a electron`
`quasar dev -m electron -t mat`

Soln fo now, `quasar mode` does `npm install` generating package-lock.json file. Need to do yarn install manually after quasar mode command.

**Comment by nothingismagick** [comment]
I can confirm that mixing yarn and npm is a bad experience (I had a similar but different error) and this is something we should really look into. I brought this up in #84 - and there have also been reports about [npm possibly breaking chromium41 builds](https://github.com/quasarframework/quasar/issues/1919). If it were up to me we would ditch npm everywhere and install yarn if the user hasn't done that already. @rstoenescu - what do you think?

**Comment by rstoenescu** [comment]
Fixed in the next CLI version with Webpack 4.
