### ISSUE TITLE
[suggestion] rename /src/css to /src/styles

### ISSUE THREAD

**Issue by beeplin** [quasarframework/quasar-cli#104]
This is trivial but people might be asking why `sr/css` can contain not only `css` files but also `styl`, `less`, `sass` files. In fact `src/styles` could be a better name.

Other than that, in editors/IDEs, currently `css`  is listed among `components` and `layouts`. After naming it to `styles`, it makes `components`, `layouts` and `pages` listed together, which is neat and meaningful:

![image](https://user-images.githubusercontent.com/13058150/38866029-35dc7638-4272-11e8-8da8-4e8396059e92.png) ---> ![image](https://user-images.githubusercontent.com/13058150/38865957-03c30d7e-4272-11e8-979a-1fe0bc458d77.png)

**Comment by nothingismagick** [comment]
I think that this is a good idea for semantic purposes, however it will have to wait until a minor version bump to v0.16 or the major v1...

**Comment by rstoenescu** [comment]
Good reasons. Will do. Most likely along the CLI update with Webpack 4 (which is not too far away).
