### ISSUE TITLE
When I close electron in dev view, webpack should close and the CLI should die.

### ISSUE THREAD

**Issue by nothingismagick** [quasarframework/quasar-cli#119]
The title says it all.

Maybe a "hang-up" approach like this could be used:

https://github.com/quasarframework/quasar-cli/commit/2028d489a147ff43e7fb4c654958278b66a7f562#diff-0dc89696c961a4ca1a547deaffa8d30c

**Comment by rstoenescu** [comment]
Available in next release (CLI v0.16)
