### ISSUE TITLE
[bug] nodejs fs module error

### ISSUE THREAD

**Issue by pinghe** [quasarframework/quasar-cli#121]
in App.vue

````
if (this.$q.platform.is.electron) {
  let fs = require('fs')
  ....
}
````

compile error executing quasar dev:

````
ERROR  Failed to compile with 1 errors  

This dependency was not found:

* fs in ./node_modules/electron/index.js

To install it, you can run: npm install --save fs
````

To solve this problem  need to modify the file quasar-cli\lib\build\webpack-config.js
````
  const webpackConfig = {
    node: {
      fs: 'empty'
    },
````

Reference to this information for a temporary solution
https://stackoverflow.com/questions/40959835/webpack-express-cannot-resolve-module-fs-request-dependency-is-expression?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

````
Read somewhere to change the node fs property. It removes the error warnings but I don't think this is a good permanent solution.

module.exports = {
  node: {
    fs: "empty"
  }
}
````

**Comment by nothingismagick** [comment]
By the way, the stack-overflow issue has has an answer since 2016: Add "target": "node"

Did you try to put this in your quasar.conf.js file?

```js
    electron: {
      extendWebpack(cfg) {
        target: 'node'
      },
```

**Comment by rstoenescu** [comment]
Try using the v0.16 CLI. Don't tamper with webpack "target".
