### ISSUE TITLE
pug support changed in 16.x?

### ISSUE THREAD

**Issue by dasantonym** [quasarframework/quasar-cli#124]
### Software version

Quasar CLI: 16.1
OS: mac os
Node: 10.1
NPM: 6.0.1
Any other software related to your bug:
Pug: 2.0.3

### What did you get as the error?

For each .vue file containing a template lang="pug" element:

```
ERROR in ./src/App.vue?vue&type=template&id=7ba5bd90&lang=pug (./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=template&id=7ba5bd90&lang=pug)
(Emitted value instead of an instance of Error) 
  Error compiling template:
  
  #q-app
    router-view
  
  - Component template requires a root element, rather than just text.

 @ ./src/App.vue?vue&type=template&id=7ba5bd90&lang=pug 1:0-203 1:0-203
 @ ./src/App.vue
 @ ./.quasar/entry.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 webpack/hot/dev-server ./.quasar/entry.js
```

### What were you expecting?

Pre-v16 i could just install pug as a dev dependency and then use the lang="pug" property to include pug formatted templates without further action. This does not seem to be the case anymore but is this expected behaviour?

### What steps did you take, to get the error?
Ran `quasar init test` to init a fresh project, added `npm i --save-dev pug`, converted the App.vue component to pug:
```pug
<template lang="pug">
   #q-app
      router-view
</template>
```
... then ran `quasar dev`.

**Comment by rstoenescu** [comment]
Vue-loader 15 (latest): https://vue-loader.vuejs.org/guide/pre-processors.html#pug

**Comment by rstoenescu** [comment]
Will include these webpack rules by default in CLI, and devs should only install the loader afterwards. This is for convenience, to not have to use quasar.conf > extendWebpack()

**Comment by dasantonym** [comment]
well i guess this is answered by a little bit of research...

once i add `npm i --save-dev pug pug-plain-loader` and then to `quasar.conf.js` webpack rules:
```javascript
      extendWebpack (cfg) {
         cfg.module.rules.push({
            enforce: 'pre',
            test: /\.(js|vue)$/,
            loader: 'eslint-loader',
            exclude: /(node_modules|quasar)/
         }, {
            test: /\.pug$/,
            loader: 'pug-plain-loader'
         })
      },
```

It works again and everthing's fine. Only question would be if this is a deliberate decision or a bug?

**Comment by dasantonym** [comment]
oh i now saw your comments, thanks for the quick response! should have looked up the link earlier...

**Comment by rstoenescu** [comment]
It's a vue-loader change. Out of Quasar's reach. And it's deliberate on their end.

**Comment by rstoenescu** [comment]
Added this to docs too. Might be good for others with the same goal.
