### ISSUE TITLE
package.json lists engine:npm after init with yarn

### ISSUE THREAD

**Issue by nothingismagick** [quasarframework/quasar-cli#129]
This seems like a no-brainer, but for the life of me I don't know where to look to solve this...

**Comment by rstoenescu** [comment]
Added yarn too. https://github.com/quasarframework/quasar-starter-kit/commit/777843b14ae394c8c4c4293a867aa13d5e3953cd

The "engine" field is advisory. It does not mean only npm or only yarn should be specified. Both are better, since user can later install with both.
