### ISSUE TITLE
Quasar commands problem on Windows Node v10.3

### ISSUE THREAD

**Issue by pedroivorbgrodrigues** [quasarframework/quasar-cli#130]
### Software version

OS: Windows Pro x64 Version 1709 (OS Build 16299.431)
Node: v10.3.0
NPM: 6.1.0
Any other software related to your bug:
Tried with yarn too, same result.
### What did you get as the error?
No error, just hangs,
### What were you expecting?
When running quasar info expected something like the sample output from the docs.
When running quasar init expected it to create the folder and bootstrap the contents.
### What steps did you take, to get the error?

1. Fresh installed latest nodejs.
2. Open powershell
3. npm install -g vue-cli
4. npm install -g quasar-cli
5. Reopenned Powershell to get the updated PATH variables
6. quasar info

![quasar_problem](https://user-images.githubusercontent.com/293789/40692507-a4b00426-6388-11e8-8cc1-bf9e9d0814e8.png)

**Comment by pedroivorbgrodrigues** [comment]
Node LTS version works.

**Comment by pdanpdan** [comment]
please try:
```
npm -g uninstall vue-cli
npm -g i @vue/cli @vue/cli-init

quasar init test
cd test
quasar info
```
