### ISSUE TITLE
service-worker doesn`t work in subdirectory

### ISSUE THREAD

**Issue by scarry1992** [quasarframework/quasar-cli#131]
https://github.com/quasarframework/quasar-cli/blob/36b745cef4c438ab4c9483b808730e733ccf1a7a/lib/quasar-config.js#L472
I deploy app in subdirectory in gh-pages, and sw doesn`t register, because it has '/' in base path.

**Comment by rstoenescu** [comment]
Yes, it doesn't, due to browser restrictions.
Only deploy a PWA on the root folder, so no "publicPath".

**Comment by scarry1992** [comment]
But if root of my project will be like https://my-scope.github.io/BlahProject/, then sw will not be registered at the root and will not work.
