### ISSUE TITLE
Compile Errors: Module build failed: ... 'objectRestSpread' isn't currently enabled

### ISSUE THREAD

**Issue by altShiftDev** [quasarframework/quasar-cli#132]
### Software version

OS: OSX 10.12.6 (Sierra) (Darwin(16.7.0) - darwin/x64)
Node: v9.8.0
Yarn: 1.7.0
NPM: 6.0.1 (Using Yarn though)
Quasar-CLI: 0.16.3
quasar-framework: 0.16.0
vue-cli: 2.9.3
cordova: 8.0.0

Any other software related to your bug:
Quasar with Cordova Mode

### What did you get as the error?
```
 ERROR  Failed to compile with 1 errors                                                          12:15:19

 error  in ../.quasar/entry.js

Syntax Error: Support for the experimental syntax   'objectRestSpread' isn't currently enabled (40:3):
    38 |   router,
    39 |
  > 40 |   ...App
       |   ^
    41 | }
    42 |
    43 |
  Add @babel/plugin-proposal-object-rest-spread (https://git.io/vb4Ss) to the 'plugins' section of your B  abel config to enable transformation.

  - index.js:3861 Parser.raise
    [myApp]/[@babel]/parser/lib/index.js:3861:15

  - index.js:5195 Parser.expectPlugin
    [myApp]/[@babel]/parser/lib/index.js:5195:18

  - index.js:6602 Parser.parseObj
    [myApp]/[@babel]/parser/lib/index.js:6602:14

  - index.js:6234 Parser.parseExprAtom
    [myApp]/[@babel]/parser/lib/index.js:6234:21

  - index.js:5868 Parser.parseExprSubscripts
    [myApp]/[@babel]/parser/lib/index.js:5868:21

  - index.js:5847 Parser.parseMaybeUnary
    [myApp]/[@babel]/parser/lib/index.js:5847:21

  - index.js:5754 Parser.parseExprOps
    [myApp]/[@babel]/parser/lib/index.js:5754:21

  - index.js:5726 Parser.parseMaybeConditional
    [myApp]/[@babel]/parser/lib/index.js:5726:21

  - index.js:5673 Parser.parseMaybeAssign
    [myApp]/[@babel]/parser/lib/index.js:5673:21

  - index.js:7701 Parser.parseVar
    [myApp]/[@babel]/parser/lib/index.js:7701:26

 @ multi ../node_modules/webpack-dev-server/client?http:// <-- ip-redacted -->:8080 webpack/hot/dev-server ../.quasar/entry.js
```
### What were you expecting?
The command to work and the repo to compile OR to receive an error relating to your current directory path.

### What steps did you take, to get the error?
If you issue the quasar dev/build commands from inside the `src-cordova` folder you will get the errors above. This is new behavior for the 0.16 Quasar version and did not occur a few weeks ago. It would be good to either restore the old behavior and allow these commands to work OR to catch the error and display a useful message to the user indicating how to fix it.

**Comment by rstoenescu** [comment]
Hi,

This is due to the new Babel v7. It seems like it only takes into consideration the .babelrc of the current folder, instead of going up to the root folder and looking for it. Fixed it and will be available in CLI v0.16.4.

Thank you for offering the important detail that it fails when in src-cordova, which helped me fix this easily.
