### ISSUE TITLE
[REQUEST] quasar-cli does not allow relative publicPath

### ISSUE THREAD

**Issue by solaris7791** [quasarframework/quasar-cli#139]
Hello,

if the applications path is not absolute (for ex. if it should run behind a reverse-proxy), than its required to have a relative uri for resource loading and routing.
If we use publicPath in quasar.conf.js it will be processed in quasar-config.js in formatPublicPath function and a slash is prefixed. 
It would be nice, if publicPath would be only made absolute if path does not start with './' or it would be perhaps better to just avoid the prefixing with a slash

thx

**Comment by rstoenescu** [comment]
Hi,

Due to Webpack restrictions, the publicPath needs to be absolute & needs to be known at compile time. Cannot change to relative path, unfortunately. Sorry for any incoveniences.

**Comment by solaris7791** [comment]
hi,
yes, you are right. But it works, just fine if i remove the checks and the prefixing ;)
I would guess, it would be perhaps better to let webpack decide, or perhaps display just a warning in quasar-cli build. What do you think?
thx
