### ISSUE TITLE
quasar build css separated folder

### ISSUE THREAD

**Issue by lei-cao** [quasarframework/quasar-cli#141]
Hi,

Currently, `quasar build` will generate all css files into root path of the dist app folder. 
There are many of them and it's hard to manage. It's not having the same conversion as js, img, fonts etc (in the separated folders).
Like 
css: https://github.com/quasarframework/quasar-cli/blob/dev/lib/build/webpack-config.js#L332
and 
js: https://github.com/quasarframework/quasar-cli/blob/dev/lib/build/webpack-config.js#L245

Also due to my server limitation, I need to serve css, js, fonts etc in separated static folders and serve the index.html separately. I can't directly server the root dist app path for all files. 

Is it possible to move the css files into separated folder? Currently I am updating it in my own version. 

Cheers,
Lei

**Comment by rstoenescu** [comment]
Hi,

CSS will be extracted into /css instead of root.
Available in next Quasar CLI version.

**Comment by lei-cao** [comment]
this is great! thanks @rstoenescu
