### ISSUE TITLE
Service worker in subdirectory

### ISSUE THREAD

**Issue by mardom1** [quasarframework/quasar-cli#142]
Hello,
as #131 seems to be closed, I am creating a new issue.

Like the author of #131, I am deploying my PWA to a subdirectory on our server. In previous versions this worked perfectly fine after specifying the public path.
But after updating to Quasar CLI v16 the public path is ignored for the service worker, so that the PWA is trying to load `/service-worker.js` instead of `/publicPath/service-worker.js`.
This impacts greatly on user experience, with no offline functionality and updating.

#131 was closed with the argument that it isn't possible due to browser restrictions, but as I said, it worked before and I can't deploy it to the server root as suggested.

I hope this gets fixed as I really like the framework.

**Comment by dexif** [comment]
Yes it's very important for us too!

**Comment by nadezhdamosunova** [comment]
+1

**Comment by LeXXaT** [comment]
+

**Comment by keano19** [comment]
+1

**Comment by oleg-omelyusik** [comment]
+1

**Comment by janlycka** [comment]
+1

I've been struggling with the very same issue. Moreover, it would make more sense for anyone to deploy PWAs in non-root directories by default, e.g. https://example.com/pwa rather than https://example.com. Requiring to register a new domain for every app, as at present, is tiresome.

How come there are so few of us complaining?

**Comment by rstoenescu** [comment]
I triple checked this. Last time I did it, Chrome tried to get the service worker from root (even though the pwa config was flawless), not from the subfolder -- bug in browser. Will check again and see if they fixed it near the end of the week.

**Comment by dexif** [comment]
Mmmm... But why on 15 version everything is ok? Just look into devtools->application->serviceworkers on https://flespi.io/toolbox
Maybe we misunderstood each other?! ;)

Google Chrome 65.0.3325.162 - ok
Opera Developer 55.0.2955.0 - ok
Firefox 61 - ok

**Comment by rstoenescu** [comment]
Probably because v0.16 deals with PWAs through the new and recommended (and future of PWAs) package called Workbox, and <= 0.15 uses the old sw-precache... Like I said, gonna make one more try. Hope it works out.

**Comment by rstoenescu** [comment]
Ok, good news! Tested with Chrome 64 and I can confirm that the browser error is no longer reproducing, so they must have fixed it. So starting with next Quasar CLI version (releasing beta in a few days) you'll be able to deploy PWAs on subfolders.
