### ISSUE TITLE
[0.17 beta] dev server not starting when using no-vuex template

### ISSUE THREAD

**Issue by panstromek** [quasarframework/quasar-cli#145]
If I init new app in Quasar v.16 and choose not to use vuex, then change CLI version to 0.17beta, npm install and try to run quasar dev mat, it crashes with 'enoent: no such file or directory .../store/index.js'

**Comment by rstoenescu** [comment]
Yes, already fixed in beta.16. Latest is beta.17 now. Thanks for reporting though!

**Comment by rstoenescu** [comment]
Oops, another issue arose. Reopening. Will be fixed in beta.18
