### ISSUE TITLE
generated files are not cleaned up on every build

### ISSUE THREAD

**Issue by panstromek** [quasarframework/quasar-cli#146]
If I have different version of CLI + project on different branch, switch branches, npm install and run `quasar dev mat`, it crashes on some missing files. 

If I delete `.quasar` folder and run `quasar dev mat` again. Everything works.

**Comment by rstoenescu** [comment]
Problem fixed starting with CLI v0.17

**Comment by rstoenescu** [comment]
But please note that it won't work if switching to/from prior CLI versions.
