### ISSUE TITLE
EPERM error during build on windows 10

### ISSUE THREAD

**Issue by kasperfish** [quasarframework/quasar-cli#147]
![image](https://user-images.githubusercontent.com/5130772/42778106-5bbf745c-893c-11e8-99a5-302d7f4c485d.png)
Have tried running the cmd with admin rights but error persists.
node
v8.11.2
npm
5.6.0

**Comment by panstromek** [comment]
This seems like you don't have right permissions in dist folder - or the program doesn't have it.. Admin rights doesn't help you, you need to modify permissions. 

Not Quasar-cli problem, probably.
