### ISSUE TITLE
Bug: Quasar Dev command not watching file changes

### ISSUE THREAD

**Issue by MatanYed** [quasarframework/quasar-cli#148]
Hi, i have problem with `quasar dev` command
when i run the command, everything works fine, but when i change .vue or .scss file content and click `ctrl+s` (save), webpack ignore the change and not refreshing the bundle.
When i change file name or change file location, it's watching fine, but change file contents - no

i tried to create new quasar project, but the issue still happens

i had this issue the past in other os (ubuntu 14.04) but then i just used the `watch-poll` option and it fixed the problem, currently there is no more watch-poll option 

ubuntu 18.04
node v. 8.11.3 (tried with v10 also)
npm 6.2.0
quasar-cli 0.16.4
quasar project 0.16.0

anyone also experience this issue? need help here...

**Comment by ldenblyd** [comment]
same issue for me 
ubuntu 18.04
node v. 8.11.3
npm 5.6.0
quasar project 0.17.3
