### ISSUE TITLE
[Bug] strip-ansi causes script error in IE11

### ISSUE THREAD

**Issue by solaris7791** [quasarframework/quasar-cli#156]
hello,
with,
Quasar CLI........ v0.17.3
Quasar Framework.. v0.17.2
strip-ansi/index.js
causes a script error in IE11 as the module.exports uses a lambda function.
I am running quasar in webpack-dev-server, looks like the imports are not transpiled

**Comment by rstoenescu** [comment]
Would you be so kind as to make the following test? Add "strip-ansi": "3.0.1" in your package.json and yarn/npm install again. Let me know how it goes. Thank you.

**Comment by solaris7791** [comment]
hello, yes with strip-ansi: 3.0.1 it works like a charm :)
thank you

**Comment by rstoenescu** [comment]
Ok. Thank you for the reply.

It's already added in CLI, which fixes some use-cases, but it seems that adding it to app's package.json directly is best.

**Comment by rstoenescu** [comment]
Some more improvements have been made in future CLI v0.17.4
