### ISSUE TITLE
strip-ansi is only added with 'quasar dev' - not 'quasar build'

### ISSUE THREAD

**Issue by panstromek** [quasarframework/quasar-cli#158]
if I remove the dependency, do a fresh npm install and then dev mat, cli installs strip ansi and adds it to package.json , 

If I do the same but do `quasar build` instead of `dev mat` it builds the project without adding strip-ansi - and this build doesn't work in Edge (same bug that was fixed with adding strip ansi)

**Comment by rstoenescu** [comment]
Thanks for reporting. Fix available in next CLI version (v0.17.6).

**Comment by panstromek** [comment]
you're super fast..
