### ISSUE TITLE
[minor] Bundle analyzer crashes build if there is already one running

### ISSUE THREAD

**Issue by panstromek** [quasarframework/quasar-cli#159]
If the port 8888 is taken, command crashes - not sure how much can this be solved because it uses external package..

but build was successful, so I guess it would be useful to catch this error and inform users that build succeded but 8888 port is taken.

**Comment by nothingismagick** [comment]
Although this is theoretically a valid report and an edge case that should be handled, I am a little surprised that you didn't fill out the entire issue form. Also, it seems you are not aware of how quasar-cli works and what could theoretically be done to resolve this issue.

**Comment by panstromek** [comment]
@nothingismagick not sure what's your point..

**Comment by ffarella** [comment]
@panstromek 
try this:
<pre>
extendWebpack (cfg) {
        /* stuff above... */
        cfg.plugins.forEach(e => {
          try {
            if (e.opts.hasOwnProperty('openAnalyzer')) {
              e.opts.openAnalyzer = false; // if you dont want to open
              e.opts.analyzerPort = 8887;; // whichever port you need
            }
          } catch (error) {}
        });
      }
<pre>
