### ISSUE TITLE
pthread_create: Resource temporarily unavailable

### ISSUE THREAD

**Issue by juanigonvocal** [quasarframework/quasar-cli#162]
### Software version
OS:  `Linux cloud6.hostgator.com 3.10.0-693.17.1.2.ELK.el6.x86_64 #1 SMP Thu Feb 8 23:35:45 MST 2018 x86_64 x86_64 x86_64 GNU/Linux
`
Node: 8.11.3
NPM: 6.3.0
Quasar-cli 0.16.4
Any other software related to your bug:

### What did you get as the error?
`$ quasar build`
outputs:
```
[==================  ] 90% (chunk assets processing)node[93]: pthread_create: Resource 
  temporarily unavailable
  Error: TypeError: child.send is not a function
    
    - fork.js:23 fork
      [my-site]/[worker-farm]/lib/fork.js:23:9
```

**Comment by nothingismagick** [comment]
Please update your quasar-cli - it should be 0.17.6

**Comment by jigarzon** [comment]
@nothingismagick thank you, how should I update? `npm update -g quasar-cli` leads me to 0.16.5

**Comment by nothingismagick** [comment]
```
$ npm update -g quasar-cli@0.17.6 

# Also update the field in your project's package.json by running 
$ npm install quasar-cli@0.17.6
```

**Comment by jigarzon** [comment]
Still happening with 0.17.6

**Comment by nothingismagick** [comment]
perhaps I should have continued reading through to the error.
    - fork.js:23 fork
      [my-site]/[worker-farm]/lib/fork.js:23:9

That looks like something from your code, because lib/fork.js does not ring a bell - and that is where the error is being thrown... I am not sure this has anything to do with quasar.

**Comment by nothingismagick** [comment]
@jigarzon - have you tried using a search engine? I found literally dozens of answers, such as:

http://unix.stackexchange.com/questions/253903/ddg#255603

Please close this issue.

**Comment by jigarzon** [comment]
@nothingismagick Yes, I'd already read that link before opening this issue. But its not related to it because this has nothing to do with `docker` and I can build other npm projects there.
I fully understand its an OS issue, but I need to understand how to properly configure quasar in order to build this, I'm sure other may have the same problem.
This is the complete stacktrace:
```
[==================  ] 90% (chunk assets processing)node[295]: pthread_create: Resource temporarily unavailable
  Error: TypeError: child.send is not a function
    
    - fork.js:23 fork
      [my-site]/[worker-farm]/lib/fork.js:23:9
    
    - farm.js:106 Farm.startChild
      [my-site]/[worker-farm]/lib/farm.js:106:16
    
    - farm.js:279 Farm.processQueue
      [my-site]/[worker-farm]/lib/farm.js:279:10
    
    - farm.js:307 Farm.addCall
      [my-site]/[worker-farm]/lib/farm.js:307:8
    
    - farm.js:38 Farm.<anonymous>
      [my-site]/[worker-farm]/lib/farm.js:38:10
    
    - index.js:71 _class.boundWorkers
      [my-site]/[uglifyjs-webpack-plugin]/dist/uglify/index.js:71:24
    
    - index.js:96 enqueue
      [my-site]/[uglifyjs-webpack-plugin]/dist/uglify/index.js:96:17
    
    - util.js:16 tryCatcher
      [my-site]/[bluebird]/js/release/util.js:16:23
    
    - promise.js:512 Promise._settlePromiseFromHandler
      [my-site]/[bluebird]/js/release/promise.js:512:31
    
    - promise.js:569 Promise._settlePromise
      [my-site]/[bluebird]/js/release/promise.js:569:18
    
    - promise.js:614 Promise._settlePromise0
      [my-site]/[bluebird]/js/release/promise.js:614:10
    
    - promise.js:689 Promise._settlePromises
      [my-site]/[bluebird]/js/release/promise.js:689:18
    
    - async.js:133 Async._drainQueue
      [my-site]/[bluebird]/js/release/async.js:133:16
    
    - async.js:143 Async._drainQueues
      [my-site]/[bluebird]/js/release/async.js:143:10
    
    - async.js:17 Immediate.Async.drainQueues
      [my-site]/[bluebird]/js/release/async.js:17:14

```

**Comment by nothingismagick** [comment]
So it seems I spoke too soon again:

```
npm ls "worker-farm"
/quasar_test_project
└─┬ quasar-cli@0.17.6
  └─┬ uglifyjs-webpack-plugin@1.2.7
    └── worker-farm@1.6.0
```

Your exact error led me to this issue at the worker-farm repo:

https://github.com/rvagg/node-worker-farm/issues/72
https://npm.community/t/npm-ci-failed-child-send-is-not-a-function/726

Can you please try to build this project with yarn instead of npm, and if it still fails please try with node 10.4.1+

**Comment by jigarzon** [comment]
I'm not using npm directly, I'm using `quasar build` command directly. Is there a way to instruct quasar cli to use yarn instead of npm?

**Comment by nothingismagick** [comment]
I assume you used npm to build your project. Do it again with yarn would be the updated advice.

**Comment by nothingismagick** [comment]
Are you still having this issue?

**Comment by jigarzon** [comment]
@nothingismagick  Yes, I found another way to resolve. I think it might be a low resource server. Please close this issue, I had opened it with another account and I lost it.

**Comment by leepowellcouk** [comment]
@jigarzon What did you do to resolve? I am hitting this error, and am having to disable uglify minification from my webpack config.

**Comment by jigarzon** [comment]
@leepowellcouk  I build on my machine and upload to the limited server manually... Please tell me if you find the way.

**Comment by nothingismagick** [comment]
@leepowellcouk - can you explain more about your environment?
