### ISSUE TITLE
[Bug] quasar build deletes previous dist folder before build is complete

### ISSUE THREAD

**Issue by rossity** [quasarframework/quasar-cli#165]
When running `quasar build`, the current process is

1. delete `dist/<build-type>`
2. build project
3. place build files in `dist/<build-type>`

I'm running `quasar build` as part of the deployment process on my server so that results in a large gap of time where the server can't find any files for the project. Would it be possible to change the process so it goes:

1. build project
2. delete `dist/<build-type>`
3. place build files in `dist/<build-type>`

That way there is virtually no downtime on the production app!

**Comment by rossity** [comment]
Would it be as simple as moving [this line](https://github.com/quasarframework/quasar-cli/blob/dev/bin/quasar-build#L130) into the [finalize promise?](https://github.com/quasarframework/quasar-cli/blob/dev/bin/quasar-build#L168)

**Comment by rstoenescu** [comment]
Hi,

Good way: build > copy dist folder somewhere > serve from there
Bad way: build (so dist folder gets generated) > delete dist > ending up with no dist folder :)

PS: the dist/* folders can be standalone by themselves.

**Comment by rossity** [comment]
@rstoenescu thanks for the response! I didn't mean delete the dist folder, I just meant is it possible to move the `artifacts.clean(outputFolder)` until _just_ before the the build files are placed in the output folder? It's nice to be able to serve from the /dist without having to write any copy scripts!

**Comment by mstaack** [comment]
@rossity i would prefer buidling  the application in a vm/container/local . and then publish that build (dist folder) to production.

**Comment by rossity** [comment]
@mstaack I use scripts automatically push my code to the production server whenever I push to the master branch of my version control. Trying to automate it as much as possible! I don't like including the /dist folder (or built files) in version control which is why I don't build locally.

**Comment by mstaack** [comment]
@rossity ok... sounds good ;)

**Comment by rossity** [comment]
Quick and dirty solution for anyone who runs across this

1. Create a folder in project named `scripts` with a file named `transfer.js`
```js
const fs = require('fs-extra')

const folder = process.argv[2]

async function execute() {
  try {
    await fs.emptyDir('./public')
    console.log('Deleted public folder contents!')
    await fs.copy(`./dist/${folder}`, './public', { overwrite: true })
    console.log('Installed new files in public folder!')
  } catch (err) {
    console.error(err)
  }
}

execute()
```

2. In `package.json`
```js
"scripts": {
    "transfer": "node scripts/transfer.js"
  }
```

3. run `yarn transfer <folder-name>` with `<fodler-name>` being whatever build the project is: `spa-mat`,  'pwa-ios` etc.

Tweak it however you liked but that worked well for me and is pretty fast even for a large project, thanks @rstoenescu for the idea!
