### ISSUE TITLE
quasar build error help

### ISSUE THREAD

**Issue by mdhhdm** [quasarframework/quasar-cli#166]
create a spa template project
then build for product , an error occurred
![43877742-1b14c372-9bce-11e8-8719-bcd68611a782](https://user-images.githubusercontent.com/7555815/43878107-f62779c2-9bcf-11e8-805c-ed22199da9cf.png)

**Comment by rstoenescu** [comment]
Hi, I already told you the steps to follow on https://github.com/quasarframework/quasar/issues/2403
Why opening this again?

**Comment by mdhhdm** [comment]
I have tried `yarn` , same error
I will try discord for help
