### ISSUE TITLE
[PWA] navigationFallback workbox option is not recognized

### ISSUE THREAD

**Issue by steebchen** [quasarframework/quasar-cli#167]
## Summary
I want to use [Workbox' navigationFallback option](https://developers.google.com/web/tools/workbox/guides/generate-complete-sw#navigation_fallback) in the PWA options in quasar.conf.js, but I get the following error:

```
(node:10157) UnhandledPromiseRejectionWarning:   ValidationError: "navigationFallback" is not a supported parameter.
  - errors.js:190 Object.exports.process
    [...]/[joi]/lib/errors.js:190:19
  - index.js:668 internals.Object._validateWithOptions
    [...]/[joi]/lib/types/any/index.js:668:31
  - index.js:702 internals.Object.validate
    [...]/[joi]/lib/types/any/index.js:702:21
  - validate.js:20 module.exports
    [...]/[workbox-build]/build/entry-points/options/validate.js:20:33
  - generate-sw-string.js:36 _callee$
    [...]/[workbox-build]/build/entry-points/generate-sw-string.js:36:2    3
  - new Promise
  - _export.js:36 new F
    [...]/[core-js]/library/modules/_export.js:36:28
  - generate-sw-string.js:62 generateSWString
    [...]/[workbox-build]/build/entry-points/generate-sw-string.js:62:1    7
  - generate-sw.js:155 GenerateSW._callee$
    [...]/[workbox-webpack-plugin]/build/generate-sw.js:155:24
```

## The long story
Everything with the SW works fine, but it seems that if you request a page (like in a new tab by entering its url) other than /, the service worker does not pick up the request. Now what I've done is added the runtimeCaching option with my routes – now it gets picked up when I have visited that specific page before. However, I want the SW to pick up all pages, even if they didn't get visited before. In Workbox, there is an option called navigationFallback which is probably the correct option for what I want to achieve, but adding it to the pwa config in quasar.conf.js results in the error above.

My first thought was an outdated workbox-webpack-plugin version, but it seems it's the latest version (3.4.1).

### Software version

OS: Linux Mint 18.2
Node: v9.11.1
NPM: 6.3.0

**Comment by rstoenescu** [comment]
Hi,

No, that will not help you at all.
What you need is to configure runtimeCaching and add all your routes. It also depends on whether you use "history" or "hash" mode as Vue Router mode.

```
{
   urlPattern: /\/jobs/,
   handler: 'networkFirst' // or other Workbox strategies
}
```

**Comment by steebchen** [comment]
Thanks for the fast reply, but I think we're not talking about the same thing. I am already using the runtimeCaching options with all my routes, even dynamic ones, and it works fine. I use the cacheFirst option so it always retrieves all routes from the cache. The problem is that the SW is not catching requests which are not in the cache yet. For example, if you visit / and /user/steebchen, close the tab and then open /user/rstoenescu in a new one – the SW could intercept that but is actually not.

**Comment by rstoenescu** [comment]
Whatever Workbox offers that's what you'll get. Which is why I think this ticket / question is misplaced. You should engage with workbox team/forum/chat instead.

You haven't specified if you're building a PWA or a SSR + PWA so I can offer you more details as time allows.

**Comment by steebchen** [comment]
Yeah, I was pretty sure it was not Workbox fault because it was in their docs and everything seemed fine – turns out the parameter actually has a slightly different name. I created an [issue](https://github.com/GoogleChrome/workbox/issues/1605) on the Worbkox repo. Sorry for the trouble, I should have researched more.
