### ISSUE TITLE
quasar build error Cannot find module '@babel/runtime/core-js/get-iterator'

### ISSUE THREAD

**Issue by ralphchristianeclipse** [quasarframework/quasar-cli#171]
Okay just moved this too here

with this package.json i have

![image](https://user-images.githubusercontent.com/25447231/44616822-a3639b00-a889-11e8-9ac2-ff87a2cd0587.png)

![image](https://user-images.githubusercontent.com/25447231/44616818-83cc7280-a889-11e8-8694-fac5c720c244.png)

**Comment by ralphchristianeclipse** [comment]
Okay https://github.com/haytko/apollo-link-watched-mutation

this repo makes the issue

**Comment by chefkoch333** [comment]
Hi, did you fix the issue, I am facing currently the same error.

**Comment by onexdata** [comment]
I also have this error... does anyone know what's causing it? I'm not using Apollo
