### ISSUE TITLE
[bug] quasar build is broken with cli 0.17.19

### ISSUE THREAD

**Issue by solaris7791** [quasarframework/quasar-cli#188]
Hello,
with current quasar-cli 0.17.19 quasar build is broken and shows the error bellow:

 Build mode........ spa
 Quasar theme...... mat
 Quasar CLI........ v0.17.19
 Quasar Framework.. v0.17.16
 Debugging......... no

 app:quasar-conf Reading quasar.conf.js +0ms
 app:webpack Chaining SPA Webpack config +2s
(node:16256) UnhandledPromiseRejectionWarning:   ValidationError: Compression Plugin Invalid Options
  options should NOT have additional properties

  - validateOptions.js:32 validateOptions
    [app]/[schema-utils]/src/validateOptions.js:32:11

  - index.js:55 new CompressionPlugin
    [app]/[compression-webpack-plugin]/dist/index.js:55:31

  - Plugin.js:13 init
    [app]/[webpack-chain]/src/Plugin.js:13:18

  - Plugin.js:59 Object.toConfig
    [app]/[webpack-chain]/src/Plugin.js:59:22

  - Config.js:129 clean.Object.assign.plugins.plugins.values.map.plugin
    [app]/[webpack-chain]/src/Config.js:129:61

  - Array.map

  - Config.js:129 module.exports.toConfig
    [app]/[webpack-chain]/src/Config.js:129:40

  - index.js:16 getWebpackConfig
    [app]/[quasar-cli]/lib/webpack/index.js:16:31

  - index.js:34 getSPA
    [app]/[quasar-cli]/lib/webpack/index.js:34:10

  - index.js:123 module.exports
    [app]/[quasar-cli]/lib/webpack/index.js:123:12

  - quasar-config.js:739 QuasarConfig.compile
    [app]/[quasar-cli]/lib/quasar-config.js:739:46

  - quasar-build:120 build
    [app]/[quasar-cli]/bin/quasar-build:120:16

  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7

  - loader.js:745 Function.Module.runMain
    internal/modules/cjs/loader.js:745:11

  - node.js:279 startup
    internal/bootstrap/node.js:279:19

  - node.js:752 bootstrapNodeJSCore
    internal/bootstrap/node.js:752:3

(node:16256) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16256) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by rstoenescu** [comment]
This has already been reported and fixed in next Quasar CLI version (to be released).

Remove quasar.conf > build > gzip prop to temporarily fix the build.
