### ISSUE TITLE
quasar dev/build "Failed to compile with X errors" but no error shown

### ISSUE THREAD

**Issue by huafu** [quasarframework/quasar-cli#193]
### Software version

OS: Darwin 17.7.0 x86_64 i386
Node: 10.12.0
NPM: 6.4.1
yarn: 1.10.1
lerna: 3.4.3

### What did you get as the error?

```
❯ yarn start # => quasar dev -m pwa -H app.local.exmaple.com, but with defaults it is the same
yarn run v1.10.1
$ quasar dev -m pwa -H app.local.example.com

 Dev mode.......... pwa
 Quasar theme...... mat
 Quasar CLI........ v0.17.20
 Quasar Framework.. v0.17.17
 Debugging......... enabled

 app:quasar-conf Reading quasar.conf.js +0ms
 app:dev Checking listening address availability (app.local.example.com:8080)... +7ms
 app:workbox [GenerateSW] Will generate a service-worker file. Ignoring your custom written one. +1s
 app:workbox ⚠️  Forcing PWA into the network-first approach to not break Hot Module Replacement while developing. +1ms
 app:webpack Chaining PWA Webpack config +1ms
 app:generator Generating Webpack entry point +20ms
 app:dev-server Booting up... +4ms


  PWA █████████████████████████ [100%] in ~1s



 ERROR  Failed to compile with 8 errors 
```
(that is ALL the output)

### What were you expecting?

A list of errors so that I can debug/fix them ;-)

### What steps did you take, to get the error?

I created a lerna mono repo using yarn workspaces. Then created my Quasar App in packages/app, and at the end I asked it to let me install dependencies, at which step I came back in the root of my mono repo and ran `lerna bootstrap` to make it install dependencies.

**Comment by hipertracker2** [comment]
I have the same error but I use npm, not yarn. :(There are no error details.

**Comment by rstoenescu** [comment]
@hipertracker2 Did you notice `Error: Unknown import from Quasar: vualidate` in your error above? Are you trying to add "vualidate" (actually "vuelidate"?) in quasar.conf.js > framework > components? Cause that's not the way, that is the place for importing Quasar components only.
