### ISSUE TITLE
[Request] Add option to skip cordova build commands

### ISSUE THREAD

**Issue by okatsuralau** [quasarframework/quasar-cli#195]
When building a quasar app for production using ci tools like Fastlane.tools or Bitrise.io, it is usually preferable to run the build command to create the release version manually or using scripts provided by the tools.

Currently, the `quasar build -m cordova` automatically runs the cordova build command.

It would be nice to have an option to skip this build and just generate the output content in the `www` folder with the required injected codes.

**Comment by rstoenescu** [comment]
Will do.

**Comment by agierus** [comment]
Thanks.  I need this as well.

**Comment by andreipopovici** [comment]
I'm also trying to figure out a good way to use `fastlane` with Quasar. There's a Cordova plugin for `fastlane`, but it assumes it'll run inside `src-cordova` with an existing `www/` folder, which no longer applies for Quasar mobile builds.

@okatsuralau Would you mind sharing your `fastlane` setup for Quasar? I'm in the middle of writing a custom local action to run `quasar build -m cordova`, but there must be a better way.

**Comment by rstoenescu** [comment]
Done for v1.

CLI for future v1.0 has "$ quasar build -m electron/cordova --ui-only" --> notice "--ui-only" param.

**Comment by andreipopovici** [comment]
Hi there. How could we get our hands on a v1.0-beta with `--ui-only` included?

A quick search turned up nothing: https://github.com/quasarframework/quasar-cli/search?q=--ui-only&unscoped_q=--ui-only

**Comment by andreipopovici** [comment]
Ah, it looks like it's not part of `quasar-cli` but `quasar` itself now: https://github.com/quasarframework/quasar/commit/489f62a43714141a7d776f0be48ddfab0d74f137

**Comment by syonip** [comment]
For future google searchers that end up here, it seems this command is now `--skip-pkg` or just `-s`
