### ISSUE TITLE
cant install quasar-cli with npm or yarn

### ISSUE THREAD

**Issue by ZZZubec** [quasarframework/quasar-cli#204]
### Software version

OS: Windows
Node: 9.5.0
NPM: 6.2.0
Any other software related to your bug:
H:\develop\salamandr.dev\JS\Quazar\TestApp>npm install -g quasar-cli@latest
npm WARN deprecated @babel/preset-stage-2@7.0.0-beta.54: 👋 We've deprecated any official stage presets in favor of users explicitly opt-ing into the proposals they want to use versus any perceived convenience. You can also check https://github.com/babel/babel/issues/7770 for more information.
npm ERR! Unexpected end of JSON input while parsing near '...s":"^4.1.2","jsonfile'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Salamandr\AppData\Roaming\npm-cache\_logs\2018-11-20T08_01_56_468Z-debug.log

in LOG:
87 http fetch GET 304 https://registry.npmjs.org/fs-extra 120ms (from cache)
88 silly fetchPackageMetaData error for fs-extra@7.0.1 Unexpected end of JSON input while parsing near '...s":"^4.1.2","jsonfile'

**Comment by ZZZubec** [comment]
can fix:
npm install reinstall -g
reinstall
npm install -g quasar-cli

**Comment by rstoenescu** [comment]
Seems like an npm/yarn cache issue
