### ISSUE TITLE
Error while updating my project to quasar v0.17.18

### ISSUE THREAD

**Issue by dungeon2567** [quasarframework/quasar-cli#208]
Software version
Quasar: 0.17.18
OS: Microsoft Windows 7
Node: 10.13.0
NPM: 6.4.1

What did you get as the error?
![image](https://user-images.githubusercontent.com/31074903/49038340-d0cf2600-f1a3-11e8-829a-1d175d070ae7.png)
![image](https://user-images.githubusercontent.com/31074903/49038388-fa884d00-f1a3-11e8-8b60-1d639fdc87bf.png)

What were you expecting?
update and run normally

What steps did you take, to get the error?

npm update -g quasar-cli@lastest
npm update

**Comment by rstoenescu** [comment]
Hi,

Update from what version? And I see you've updated the global install of Quasar CLI. The only one that matters is the local CLI installation (in your project folder).

**Comment by dungeon2567** [comment]
Hi, 
I upgraded from version quasar-framework@0.15.10, thank you for the help. (I also updated the local quasar-cli from 0.15.14)

**Comment by rstoenescu** [comment]
Please follow [the Upgrade Guide](https://quasar-framework.org/guide/quasar-upgrade-guide.html) then and connect with the community on Discord for help if needed. Thank you.
