### ISSUE TITLE
Command quasar build generating empty css files

### ISSUE THREAD

**Issue by vilsonei** [quasarframework/quasar-cli#212]
### Software version

OS: Windows 10
Node: 9.4.0
NPM: 6.4.1
Any other software related to your bug:
When executing the quasar command build in quasar-cli version 0.17.22 is generating empty files in the css folder. These empty files are generating errors on some java servers, for example the jetty embedded in SpringBoot is generating error 404 (file not found). Is there a possibility to remove these empty files optimizing the final build?

**Comment by rstoenescu** [comment]
Hi,

It generates whatever your vue files style section (and other css files you are injecting) contain. Webpack generates a css file even if there's one empty `<style></style>` section in a `.vue` file, which is your case here.

**Comment by vilsonei** [comment]
> Oi,
> 
> Ele gera qualquer seção do estilo dos arquivos vue (e outros arquivos css que você está injetando). O Webpack gera um arquivo css mesmo se houver uma `<style></style>`seção vazia em um `.vue`arquivo, que é o seu caso aqui.

Thanks
