### ISSUE TITLE
[Bug] quasar build fails on shared hosting

### ISSUE THREAD

**Issue by stefanvanherwijnen** [quasarframework/quasar-cli#214]
### Software version

OS: Linux
Node: v11.4.0
NPM: v6.4.1
Any other software related to your bug:
Running on a limited resources server

### What did you get as the error?
https://pastebin.com/8Zu7R9Yr

### What were you expecting?
Successful build.

### What steps did you take, to get the error?
I am running the command on a shared hosting server. https://github.com/quasarframework/quasar-cli/issues/162 is probably the same issue, however it has not been solved as the issuer found a workaround.

If I run ```quasar build --debug``` the build finishes fine. I suspect that UglifyJS is running in non-debug mode with ```parallel: true```, which causes the server to run out of threads. However, I am not sure how to change this.

**Comment by stefanvanherwijnen** [comment]
I thought this might be a problem with the UglifyJS configuration, but it seems that with ```--debug```UglifyJS is disabled completely: https://github.com/quasarframework/quasar-cli/blob/5854d466023159703fb1d73406aaaf5ef7ec76fe/lib/webpack/create-chain.js#L274-L277
Thus no out-of-memory error because the process is never spawned. It seems that it just requires a lot of memory so unfortunately there is no 'solution'.

**Comment by rstoenescu** [comment]
Hi,

There's a solution to increase max memory allocation to a Nodejs process, but can't remember out of the top of my head. Please ask on Discord.

**Comment by stefanvanherwijnen** [comment]
Yes, I believe it is ```--max-old-space-size=<size>```
However, in my case the memory and the number of threads was limited by the hoster so it did not work.

Thanks
