### ISSUE TITLE
webpack-dev-server  "Missing Origin Validation" vulnerability

### ISSUE THREAD

**Issue by chaitanya-plylabs** [quasarframework/quasar-cli#216]
Getting "Missing Origin Validation" error from webpack-dev-server in quasar-cli dependency. It got fixed in 3.1.11. Can we get the updated version with new dependency?

**Comment by rstoenescu** [comment]
Will update and release it in 2 days.

**Comment by rstoenescu** [comment]
Upgraded dep in v0.17.23 and released it.
