### ISSUE TITLE
cordova error: Minimum supported Gradle version

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar-cli#217]
If you have a Cordova `BUILD FAILED` error similar to:

> A problem occurred evaluating project ':CordovaLib'.
> Failed to apply plugin [id 'com.android.library']
   > Minimum supported Gradle version is 4.6. Current version is 4.1. If using the gradle wrapper, try editing the distributionUrl in /path/src-cordova/gradle/wrapper/gradle-wrapper.properties to gradle-4.6-all.zip

**Comment by mesqueeb** [comment]
### solution

This is probably because you opened the project in android studio and built it once to be able to sign your android app. You can fix it by removing and re-adding android:

```
cd src-cordova
cordova platform rm android
cordova platform add android
```

Also see: [stackoverflow: Cordova build changes distributionUrl in gradle-wrapper.properties file](https://stackoverflow.com/questions/37125496/cordova-build-changes-distributionurl-in-gradle-wrapper-properties-file)

Thought I create this thread for future reference in case anyone comes looking for it.

**Comment by jhonatanyachi** [comment]
> ### solution
> This is probably because you opened the project in android studio and built it once to be able to sign your android app. You can fix it by removing and re-adding android:
> 
> ```
> cd src-cordova
> cordova platform rm android
> cordova platform add android
> ```
> 
> Also see: [stackoverflow: Cordova build changes distributionUrl in gradle-wrapper.properties file](https://stackoverflow.com/questions/37125496/cordova-build-changes-distributionurl-in-gradle-wrapper-properties-file)
> 
> Thought I create this thread for future reference in case anyone comes looking for it.

Thanks, it solved my problem.
