### ISSUE TITLE
shows version update when it is updated

### ISSUE THREAD

**Issue by jperelli** [quasarframework/quasar-cli#22]
```
 $ quasar --version

0.5.0



   ╭───────────────────────────────────────╮
   │                                       │
   │    Update available 0.4.1 → 0.5.0     │
   │   Run npm i -g quasar-cli to update   │
   │                                       │
   ╰───────────────────────────────────────╯
```

**Comment by rstoenescu** [comment]
Hi,

CLI uses `update-notifier` NPM package. Can you please open up an issue on their github page?
https://github.com/yeoman/update-notifier

Thanks for opening this! Will close this, but I if you would be so kind can you reference this issue from the ticket you open on update-notifier's?

**Comment by jperelli** [comment]
Ok, sorry to bother, I didn't realize but it stopped happening. Maybe cache related or a delay on update-notifier. Thanks!

**Comment by rstoenescu** [comment]
It's no bother at all. Any bug must be reported.
