### ISSUE TITLE
"quasar serve" not available - but as a tip on "quasar build".

### ISSUE THREAD

**Issue by bestog** [quasarframework/quasar-cli#222]
Since the command no longer exists in the cli, shouldn't the tip be removed?

https://github.com/quasarframework/quasar-cli/blob/8133f7652d77fd2cacab5abf81109b59c11634a3/lib/helpers/banner.js#L59-L64

**Comment by rstoenescu** [comment]
But "quasar serve" is available....

**Comment by bestog** [comment]
Sorry - wrong repo. I use `@quasar/cli` for >0.17. i thought this would be the repository for the cli >=1.0.

**Comment by rstoenescu** [comment]
It's available in 1.0 also.

For 1.0 we're using a kind of monorepo so @quasar/cli, @quasar/app, "quasar", etc are in the main repo.

**Comment by bestog** [comment]
Am I doing something wrong?

```
>  quasar --version
1.0.0-beta.4
```

```
>  quasar serve
app   Unknown command "serve"   +2ms
```

```
> quasar info

NodeJs - 10.12.0

Global packages
  NPM - 6.4.1
  yarn - 1.13.0
  @quasar/cli - undefined
  cordova - Not installed

Important local packages
  quasar - 1.0.0-beta.1 -- Build responsive SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-beta.4 -- Quasar Framework App CLI
  @quasar/extras - 1.0.0 -- Quasar Framework fonts, icons and animations
......
```

**Comment by rstoenescu** [comment]
Are you running through an npm script command?
If so, then you are directly running @quasar/app -- and this command (that is supplied by global @quasar/cli) is not available. So it's only available if running through the global command "quasar", not the local/project specific @quasar/app installation.

**Comment by zadigus** [comment]
I was able to make it work by installing `@quasar/cli` as a local dependency too. Here are dev dependencies:

```
"devDependencies": {
   ...
    "@cypress/webpack-preprocessor": "^4.0.3",
    "@quasar/app": "^1.0.0-beta.18",
    "@quasar/cli": "^1.0.0-beta.4",
    "@quasar/quasar-app-extension-testing": "^1.0.0-rc.5",
    "@quasar/quasar-app-extension-testing-unit-jest": "^1.0.0-beta.22",
   ...
  },
```

**Comment by spanwair** [comment]
make sure you install `npm install quasar-cli -S` 
after your code will support `quasar serve`
