### ISSUE TITLE
[BUG] Quasar 'new' command for layout

### ISSUE THREAD

**Issue by adamkpurdy** [quasarframework/quasar-cli#224]
### Software version

OS: mac OS 10.14.3 
Node: v10.14.2
NPM: 6.7.0
Any other software related to your bug:

### What did you get as the error?
Unknown custom element: <q-layout-header>
Unknown custom element: <q-layout-footer> 
### What were you expecting?
No errors regarding the header and footer in the new v1-beta generator tool
### What steps did you take, to get the error?
- quasar new layout TestLayout
- quasar new page TestPage
- added a new route pointing to the new testpage with the layout being used

<img width="781" alt="layout-footer-error" src="https://user-images.githubusercontent.com/1054644/53037840-3f411e80-3449-11e9-9cfa-1fa81c9a1b91.png">
<img width="772" alt="layout-header-error" src="https://user-images.githubusercontent.com/1054644/53037850-42d4a580-3449-11e9-85ed-de578789e104.png">

**Comment by adamkpurdy** [comment]
Here is a PR for attempted fix: https://github.com/quasarframework/quasar-cli/pull/225

**Comment by rstoenescu** [comment]
Merged the PR. Thanks!
