### ISSUE TITLE
where's the v0.17.24 tag?

### ISSUE THREAD

**Issue by lopugit** [quasarframework/quasar-cli#232]
### Software version

OS:
Node:
NPM:
Any other software related to your bug:

**Comment by dariosalviwork** [comment]
yeah, where is it? npm gives 0.17.24 as the latest version. Is there a mistake?

**Comment by rstoenescu** [comment]
Added 0.17.24 tag -> https://github.com/quasarframework/quasar-cli/releases/tag/0.17.24
