### ISSUE TITLE
This relative module was not found: 

### ISSUE THREAD

**Issue by averri** [quasarframework/quasar-cli#234]
Quasar is failing to run informing that there is a missing module that is present.

```javacript
  "dependencies": {
    "@feathersjs/authentication-client": "^1.0.11",
    "@feathersjs/feathers": "^3.3.1",
    "@feathersjs/primus-client": "^1.1.7",
    "@feathersjs/socketio-client": "^1.2.1",
    "@quasar/extras": "^1.1.3",
    "axios": "^0.18.1",
    "lodash": "latest",
    "quasar": "^1.0.0-rc.4",
    "socket.io-client": "^2.2.0",
    "vue-i18n": "^8.11.2",
    "vue-router": "^3.0.6",
    "vuex": "^3.1.1",
    "vuex-persist": "^2.0.1"
  },
  "devDependencies": {
    "@quasar/app": "^1.0.0-rc.6",
    "strip-ansi": "=3.0.1"
  },
  "engines": {
    "node": ">= 8.9.0",
    "npm": ">= 5.6.0",
    "yarn": ">= 1.6.0"
  },
```

### Software version

OS: Linux
Node: 10.6.0
NPM: 6.9.0
Any other software related to your bug:

### What did you get as the error?
```
 ERROR  Failed to compile with 1 errors                                                                                                                                                                                            5:45:19 PM

This relative module was not found:
* ../layouts/BackGroundLayout in ./src/boot/components.js
```

### What were you expecting?
Application should run in dev mode.

### What steps did you take, to get the error?
```
yarn install
yarn dev
```

**Comment by rstoenescu** [comment]
Hi,

The error is reported by Webpack. I assure you this is working flawlessly.
But regardless, the file you are importing is not located directly under /src/layouts/BackGroundLayout[.vue|.js] ... or it doesn't has a .vue or .js extension, ... or many other reasons that may not seem obvious to you. Can only help you if you can create a repo demonstrating your issue.
