### ISSUE TITLE
Add command for getting troubleshooting info

### ISSUE THREAD

**Issue by smolinari** [quasarframework/quasar-cli#27]
It would be cool to have a CLI command, which would allow users of Quasar to get a screen printout of valuable troubleshooting info such as OS, Node, NPM and Quasar versions. Users could cut and paste this info into their bug reports. 

The command could be something like `quasar info`.

I'll be glad to take on this work. During the coming week I'll put up a PR.

Any further improvements to this idea would be greatly appreciated.

Scott

**Comment by rstoenescu** [comment]
Implemented in latest Quasar CLI beta (0.15.0-beta), so closing this.
