### ISSUE TITLE
[Request] Avoid install to global

### ISSUE THREAD

**Issue by nak1114** [quasarframework/quasar-cli#35]
I want to avoid install quasar-cli to global because I avoid execute any quasar command anywhere.

I want to command below.
bash:
```bash
$ mkdir myapp
$ cd myapp
$ npm install quasar-cli
$ $(npm bin)/quasaer init .
```
powershell:
```powershell
$ mkdir myapp
$ cd myapp
$ npm install quasar-cli
$ &"$(npm bin)\quasaer.cmd" init .
```

I wrote this patch, but I don't have any MacOS device, so I can not test it.
https://github.com/nak1114/quasar-cli

**Comment by rstoenescu** [comment]
Please reopen with a reasoning on this request.
