### ISSUE TITLE
RequestError: unable to get local issuer certificate

### ISSUE THREAD

**Issue by jvukovich** [quasarframework/quasar-cli#38]
On Windows 10, 64 bit, node 7.7.4, npm 3.10.8.

C:\Users\jvukovich\.npmrc contents:
registry=http://registry.npmjs.org/
strict-ssl=false
ca=

Confirmed settings with: npm config ls -l

Executed: quasar init default#beta [folder]

Result: Failed to download App template @quasarframework/quasar-template-default#beta: RequestError: unable to get local issuer certificate

We are behind a Websense proxy and they have an in-between certificate installed to decrypt SSL traffic.

I found this: https://github.com/quasarframework/quasar-cli/issues/17

So, my .npmrc is setup properly, and settings inspection reflects them.

Anything else I am missing / ideas?

**Comment by aldanor** [comment]
Same problem here (I've posted details in #17 actually), we have a proxy with in-between certificate so this fails.

Any chance to address this so quasar is usable in corporate environments? :panda_face: 

Thanks.

**Comment by rstoenescu** [comment]
@jvukovich @aldanor does `vue init quasarframework/quasar-template-default <folder>` works for you?

**Comment by jvukovich** [comment]
I switched to the beta version a few weeks ago and it worked. But, I can't be certain our networking guys didn't change something on this end which may have also allowed it to work. Hopefully @aldanor can provide a valid test.

**Comment by rstoenescu** [comment]
@jvukovich beta or no beta version, it works the same. Most likely the networking guys did something to allow it.

**Comment by jvukovich** [comment]
@rstoenescu I meant I tested it recently by switching over to the beta. Thanks!

**Comment by aldanor** [comment]
@rstoenescu Just tried the `vue init` way, that fails as well :/

**Comment by rstoenescu** [comment]
Quasar CLI is using [download-git-repo](https://github.com/flipxfx/download-git-repo) under the covers to download the templates. If it's not working, then you should probably open up a ticket on their github page.

**Comment by jdus** [comment]
I think it's not a problem with [download-git-repo](https://github.com/flipxfx/download-git-repo), but rather the dependency of the [download](https://github.com/kevva/download) module. See [#64](https://github.com/kevva/download/issues/64)

**Comment by rstoenescu** [comment]
Hi,

This is outdated. The new Quasar CLI (0.15.0-beta) will defer project creation to "vue-cli", so if there's a problem with vue-cli too (as @aldanor stated), then please refer to vue-cli repo to post the issue with an equivalent vue-cli command to initiate a Quasar project (or any vue template out there).

Thank you.

**Comment by maxi032** [comment]
I get the same error too:

<pre>
quasar init myquasarapp
 Running command: vue init 'quasarframework/quasar-starter-kit' myquasarapp
   vue-cli Â· Failed to download repo quasarframework/quasar-starter-kit: self signed certificate in certificate chain

</pre>

**Comment by rstoenescu** [comment]
@maxi032 that's an npm server error. It's part of NPM organization management to ensure this is not happening. Not an error on our part (Quasar). I hate it when the experience with Quasar gets bashed by external factors like the NPM server. I hope it does not affect the way you perceive Quasar. If the command still doesn't works in an hour or two (usually NPM is aware of these kind of problems and fixes them quickly), then I'll show you how can generate a project folder without going through Quasar CLI or vue init.

**Comment by pgrondin27** [comment]
I had the same issue at work with our man in the middle corporate certificate. You should configure npm to manage your corporate certificate or run the following fix (insecure) to tell npm not to validate the SSL key
**npm_config_strict_ssl=false quasar create**
or with vue init
**npm_config_strict_ssl=false vue init 'quasarframework/quasar-starter-kit'** myquasarapp
