### ISSUE TITLE
postcss-loader v2 breaks quasar-cli

### ISSUE THREAD

**Issue by beeplin** [quasarframework/quasar-cli#39]
after upgrading `postcss-loader` from 1.3.3 to 2.x, `quasar dev` reports errors like `https://github.com/postcss/postcss-loader/issues/209` (in both 0.13 and 0.14beta)

According to the link above, `postcss-loader v2` no longer uses `LoaderOptionsPlugin` in the webpack config file, so the webpack configuration needs to be fixed if we are to upgrade to postcss-loader v2

**Comment by cgestes** [comment]
Even with quasar 0.15 this can be an issue if using yarn workspace.

the root repository will not contains a postcss configuration only the child packages/<mypackageusingquasar> but the quasar-extra package will be in <root>/node_modules.

Simply copying the postcss config generated by quasar at the root of quasar-extras seems to fix it.

**Comment by rstoenescu** [comment]
Postcss v2 has been included in the new starter kit, so closing this.
