### ISSUE TITLE
Quasar Build exits with 0 despite having errors or warnings

### ISSUE THREAD

**Issue by JCharante** [quasarframework/quasar-cli#40]
### Software version

OS: Ubuntu 17.10
Node: v4.7.2
NPM: 3.5.2
Any other software related to your bug:

### What did you get as the error?

Exit Code 0

### What were you expecting?

Exit Code 1? Really just anything other than 0

### What steps did you take, to get the error?

Import an unused componenet, then run `quasar build`. Despite `✘ 1 problem (1 error, 0 warnings)`, it exits with 0. I'm trying to integrate `quasar build` with Travis CI, so it would be helpful if quasar build did not exit with 0 when it encounters problems.

**Comment by JCharante** [comment]
You might wonder why I'm not using `quasar lint`. It appears that it runs `eslint --ext .js,,vue src`, which results in about 33k errors that are not seen while running `eslint --ext .vue src`. When I run `eslint --ext .vue src` it only shows 1 error, which is the same one shown during `quasar build`

**Comment by JCharante** [comment]
I managed to get what I wanted by running `./node_modules/.bin/eslint --ext .vue src/` instead of `quasar build` or `quasar lint`.

**Comment by rstoenescu** [comment]
Fix available in Quasar CLI v0.6.3 (just released).

Some changes are required to the app folder too (these changes are now available in latest default#beta starter kit -- soon to become the default one): https://github.com/quasarframework/quasar-template-default/commit/fafd43d098456945f3e6bbeabb37adaa84af1558
