### ISSUE TITLE
New OSX install fails due to 'spawn' calling files with incorrect permissions

### ISSUE THREAD

**Issue by Mark-L6n** [quasarframework/quasar-cli#44]
### Software version

OS: OSX 10.12.6
Node: 8.4.0
NPM: 5.4.0
Any other software related to your bug:

### What did you get as the error?

internal/child_process.js:325
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at _errnoException (util.js:1041:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:493:9)
    at Command.executeSubCommand (/usr/local/lib/node_modules/quasar-cli/node_modules/commander/index.js:546:14)
    at Command.parse (/usr/local/lib/node_modules/quasar-cli/node_modules/commander/index.js:471:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/quasar-cli/bin/quasar:41:4)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)

### What were you expecting?
No error

### What steps did you take, to get the error?
Running either `quasar version` or `quasar init testproj` causes the error. Brand new install of what should be v14.2.

The problem looks like it's caused by incorrect file permissions (none executable) in `/usr/local/lib/node_modules/quasar-cli/bin`, so the `spawn` command fails on these:

``` bash
-rw-r--r--    506B Oct 25  2016 quasar-build
-rw-r--r--     60B Oct 25  2016 quasar-clean
-rw-r--r--    2.8K Mar  1 10:00 quasar-dev
-rw-r--r--    2.5K Mar 31 05:08 quasar-init
-rw-r--r--     59B Oct 25  2016 quasar-lint
-rw-r--r--    937B Aug 18 08:04 quasar-list
-rw-r--r--    2.3K Nov  1  2016 quasar-new
-rw-r--r--    1.1K Apr  4 12:55 quasar-serve
-rw-r--r--    654B Oct 25  2016 quasar-test
-rw-r--r--    1.0K Mar 31 05:08 quasar-version
-rw-r--r--    1.3K Nov 15  2016 quasar-wrap
```

**Comment by harrysummer** [comment]
Same here. The following command walkarounds this.
```
sudo chmod 755 quasar-*
```

**Comment by rstoenescu** [comment]
The executable rights should have been preserved like it was for a long time. Guess either macos or newer node at fault here. Will look for a workaround. Thanks for reporting!

**Comment by rstoenescu** [comment]
Seems like a problem in NPM 5.4.0: https://github.com/npm/npm/issues/18324
Downgrade to 5.3.0.. I hate this issues...

**Comment by harrysummer** [comment]
So this issue can now be closed?

**Comment by rstoenescu** [comment]
I'd leave it open until the npm team releases a fix.

**Comment by rstoenescu** [comment]
Oh, seems like they deployed npm 5.4.1 which fixes this.
