### ISSUE TITLE
"usr/lib/node_modules/quasar-cli/bin/quasar-list(1) does not exist, try --help"

### ISSUE THREAD

**Issue by alidplus** [quasarframework/quasar-cli#48]
I install quasar-cli globaly but when i want to use commands termux throw this error:

usr/lib/node_modules/quasar-cli/bin/quasar-list(1) does not exist, try --help

/data/data/com.termux/files/usr/lib/node_modules/quasar-cli/bin/quasar-init(1) does not exist, try --help

/data/data/com.termux/files/usr/lib/node_modules/quasar-cli/bin/quasar-list(1) does not exist, try --help

But its bullshit that file exist!
I found similar issues on vue-cli but not any fix was there.

Tnx

Quasar: 0.6.4
OS: android 6 and 7 with termux
Node:6.11.2
NPM:3.10.10

**Comment by johnpaulada** [comment]
This happened to me when i used `yarn global add quasar-cli` to install quasar-cli. I removed it and installed with `npm install -g quasar-cli` and it worked.

**Comment by vitali2y** [comment]
I've installed  `quasar-cli@0.6.4` with `npm install -g quasar-cli`, but have `quasar-init(1) does not exist` error for `quasar help init`, `quasar list`, or any other, except `quasar` without command-line args (`node 8.8.1`, `npm 5.5.1`, `Linux Mint 18`).

**Comment by rstoenescu** [comment]
It's a glitch in some NPM versions. Please upgrade to latest NPM (5.6.0).

**Comment by counterpointing** [comment]
Upgrading to NPM 5.6.0 does not resolve this issue - however executing it with the full path does
