### ISSUE TITLE
SyntaxError: Use of reserved word 'export' in file quasar.esm.js

### ISSUE THREAD

**Issue by mobiusVision** [quasarframework/quasar-cli#49]
### Software version

OS: Mac 
Node:
NPM:
Any other software related to your bug:

### What did you get as the error?
SyntaxError: Use of reserved word 'export' in file quasar.esm.js
![2017-09-29 19 17 49](https://user-images.githubusercontent.com/30039085/31013950-0a4d51fa-a54b-11e7-8b33-dc4e589299b2.png)

### What were you expecting?
I'm using quasar-cli to create the webpack1&Vue2, when i finished installing all requires, it shows me the error.
### What steps did you take, to get the error?

**Comment by rstoenescu** [comment]
Hi,

Please upgrade to latest starter kit. The one you are trying to use is way outdated. Unfortunately, I don't have enough resources to investigate it at the moment, so sorry :(
