### ISSUE TITLE
[REQUEST] quasar new root folder parameter

### ISSUE THREAD

**Issue by 3kynox** [quasarframework/quasar-cli#50]
Hello !

To integrate Quasar in a client/server structure, I moved quasar root folder into a sub-folder "client" and reconfigured packages.json and webpack paths to have quasar work from its new location.

Problem : when using quasar new command and after had a look on this repository, quasar-new assume there is an src folder from the root of the project which is no longer the case in the current structure I'm using now.

I think the simpler way to correct this should be to be able to give the new location of the /src folder (and templates/ inside it) using a parameter from this command, like : 

`quasar new --list --base-path=/client/src` or
`quasar new component Hello  --base-path=/client/src`

Is it something possible to have ? Or wants me to PR ?

Thanks anyway.

**Comment by rstoenescu** [comment]
Hi,

I don't know how I totally missed this ticket. Are you interested in making a PR for "next" branch? So sorry to have missed this.

**Comment by 3kynox** [comment]
That's ok! I'll make a PR. Normally soon also to feathers repository that @claustres maintain (I talked with him already few weeks ago). I have already integrated in a working project Feathers (v3 - buzzard) with graphql server side with quasar / vue frontend side + websocket subscriptions in addition.

**Comment by nothingismagick** [comment]
Any status update here?

**Comment by rstoenescu** [comment]
Closed due to inactivity.
