### ISSUE TITLE
babel-preset-es2015 package

### ISSUE THREAD

**Issue by IamAnotherOne** [quasarframework/quasar-cli#51]
Hi, I try install quasar on windows machine, when execute command 'npm install' i got error for installing 'babel-preset-es2015' package,
According what https://babeljs.io/ told i replaced 'babel-preset-es2015' to 'babel-preset-env' and problem solved,
but later when i executed command 'quasar dev' got error:
Module build failed: Error: Couldn't find preset "es2015" relative to directory.
Is there any plan to upgrade from 'babel-preset-es2015' to 'babel-preset-env' ?
Someone has any solution for this issue?

**Comment by rstoenescu** [comment]
Yes. v0.15 is gonna get updated to babel-preset-env. If the time allows, I'll port the change to v0.14 template too.

**Comment by IamAnotherOne** [comment]
Great, you are awesome

**Comment by rstoenescu** [comment]
This is already in the new starter kit + CLI, so closing this.
