### ISSUE TITLE
[REQUEST] Allow fetching of custom templates from a private repository

### ISSUE THREAD

**Issue by FerrielMelarpis** [quasarframework/quasar-cli#54]
Hi @rstoenescu 

Thanks for the great tool.

I am currently using quasar framework to create a custom template but I encountered an issue when using a private repository. I noticed that you've used `download-git-repo` library and in the [options section](https://www.npmjs.com/package/download-git-repo#options), we can use `clone: true` to be able to download the template from private repositories.

I would like a support for passing options to `quasar init` command to be able to use `git clone` for downloading a custom template.

I can submit a PR to add the option.

**Comment by rstoenescu** [comment]
You can already do that. From the top of mind, I think this is the command:
`quasar init @github_user/name_of_repo`. If this doesn't works (can't remember and on tight schedule so no time to take a look at the old CLI version), then try without '@'.

In any case, same templates can be generated by vue-cli tool too. In fact, the new Quasar CLI relies on vue-cli to generate project folders.

**Comment by FerrielMelarpis** [comment]
No, that does not work. You need to add clone option in the download-git-repo.
https://github.com/quasarframework/quasar-cli/blob/92c54c887601a09bddfbdeca1c87f941a3ff641b/bin/quasar-init#L70-L93
It should be 
```js
// clone set by cli args
download(
    template, 
    src,
    { clone }
    function (err) {
    ...
)
```
Anyways, I was able to work it out with vue-cli.

**Comment by rstoenescu** [comment]
Like I said, the new Quasar CLI defers to vue-cli to generate a project folder, so this becomes obsolete. Glad you got it working with vue-cli.
