### ISSUE TITLE
[Bug] Yarn workspace issues with Quasar 0.15 beta

### ISSUE THREAD

**Issue by cgestes** [quasarframework/quasar-cli#56]
### Software version
OS: archlinux
Node: 9.4
NPM: yarn 1.3.2
Any other software related to your bug:

### What were you expecting?
It works.

### What steps did you take, to get the error?
start a new quasar project in a repository managed by yarn workspace.

### What did you get as the error?
```
These dependencies were not found:

* ansi-html in /home/ctaf/src/lana/node_modules/quasar-cli/node_modules/webpack-dev-server/client/overlay.js
* /home/ctaf/src/lana/packages/lana-pwa/.quasar/entry.js in multi /home/ctaf/src/lana/node_modules/quasar-cli/node_modules/webpack-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./.quasar/entry.js
* html-entities in /home/ctaf/src/lana/node_modules/quasar-cli/node_modules/webpack-dev-server/client/overlay.js
* loglevel in /home/ctaf/src/lana/node_modules/quasar-cli/node_modules/webpack-dev-server/client?http://localhost:8080
* sockjs-client/dist/sockjs in /home/ctaf/src/lana/node_modules/quasar-cli/node_modules/webpack-dev-server/client/socket.js
* strip-ansi in /home/ctaf/src/lana/node_modules/quasar-cli/node_modules/webpack-dev-server/client?http://localhost:8080
* webpack/hot in /home/ctaf/src/lana/node_modules/quasar-cli/node_modules/webpack-dev-server/client?http://localhost:8080
* webpack/hot/dev-server in multi /home/ctaf/src/lana/node_modules/quasar-cli/node_modules/webpack-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./.quasar/entry.js
* webpack/hot/emitter in /home/ctaf/src/lana/node_modules/quasar-cli/node_modules/webpack-dev-server/client?http://localhost:8080

To install them, you can run: npm install --save ansi-html /home/ctaf/src/lana/packages/lana-pwa/.quasar/entry.js html-entities loglevel sockjs-client/dist/sockjs strip-ansi webpack/hot webpack/hot/dev-server webpack/hot/emitter

```

## Temporary fix:
run ln -sf <root_repository>/node_modules packages/<myquasar_app>

Feel free to tell me how to debug / help.

**Comment by rstoenescu** [comment]
Hi. It's unclear: are you getting this on the starter kit or quasar repo?

**Comment by cgestes** [comment]
Sorry.

On the starter kit (0.15-beta27).

**Comment by cgestes** [comment]
A little bit more informations..

in [webpack-config.js](https://github.com/quasarframework/quasar-cli/blob/next/lib/build/webpack-config.js)
This type of line:
```
appPaths.resolve.app('node_modules'),
appPaths.resolve.cli('node_modules')
```
assumes that node_modules directories are in the app and cli folders, but this is not always true. (especially when using yarn workspace, the node_modules folder will be in one of the parent directory)

Some ideas to fix it:
- use [require.resolve.paths](https://nodejs.org/docs/latest/api/modules.html#modules_require_resolve_paths_request) 
- re-implement the logic looking for node_modules in parent folders
- find a package on npm that does that for us?

**Comment by rstoenescu** [comment]
Running "npm dedupe" fixes this.

When you create a new project folder you get to install quasar-cli locally. Now, all its dependencies (Quasar, webpack etc) will be installed since they are required by quasar-cli. To be sure this works with npm and yarn, the CLI tells webpack to look in those two folders where the deps should be.

Not sure what you mean by parent directory. Can you show me a tree of your node_modules? Please reopen if "npm dedupe" does not helps. Thanks

**Comment by cgestes** [comment]
a typical yarn workspace project:

```
<root>/package.json  
<root>/packages/myapp/{package.json, src, ...}
<root>/packages/myfoo/{package.json, src, ...}
<root>/node_modules/{whatever deps}
```

There is only one node_modules folder for all packages. (you can have as many packages you want in the packages folder).

See babel, pouchdb, angular, firebase, for example of multi-package repositories.

Documentation here:
https://yarnpkg.com/lang/en/docs/workspaces/

`npm dedupe` does not fix the issue.

**Comment by rstoenescu** [comment]
Having everything in `<root>/node_modules` is ideal for the CLI to work. (This is actually what "npm dedupe" does). It's not something to be considered a bug.

Please make sure you got the latest CLI when testing. To be sure, change package.json to make quasar-cli point to ^0.15.0-beta.36, delete node_modules and install with yarn again.

NPM and yarn are flaky. This is the reason why the CLI creates a webpack config to look both in <root>/node_modules and <root>/quasar-cli/node_modules. There are cases where NPM will place the CLI deps in the latter folder.

**Comment by rstoenescu** [comment]
I re-read an older post of yours (`run ln -sf <root_repository>/node_modules packages/<myquasar_app>`). Are you running this in the new starter kit or do you have a custom project folder created by you?

**Comment by rstoenescu** [comment]
@cgestes any comments? :)

**Comment by cgestes** [comment]
sorry for the delay. It was in a clean new starter kit, with everything in beta.

The problem is sadly real. I posted some pointers to the code where the module lookup implementation of quasar tools differ from the what node does.

Basically, quasar doesn't work with yarn workspaces. (at least it didnt when I reported the bug)

**Comment by MPloemen** [comment]
It seems that adding 2additional properties to `appPaths` will resolve the issue: 
- workspaceRoot: `join(appDir, '..', '..')` (which maybe can be derived from quasar.conf.js
- node_modules which uses a fs.existsSync check to determine if workspaceRoot/node_modules exists or not. 

Then replacing all references to `appPaths.resolve.app('node_modules/....)` with the new `appPaths.node_modules` or `appPaths.resolve.node_modules(some_nested_package)`. 

Additonally, the webpack alias for `quasar` needs to be changed using the same procedure.
