### ISSUE TITLE
manifest.js file is not loaded by browser after every build & release

### ISSUE THREAD

**Issue by lei-cao** [quasarframework/quasar-cli#59]
Hi,

manifest.js file doesn't have a hash in the file name, every time after I build and release the new version, the browser is still loading the older version of manifest.js, the users have to force reload or clear the browser cache to load the site correctly. 
Then since the older chunk js might have been deleted while the development, the site will break, showing errors like this:
```
Error: Loading chunk 0 failed.
r — manifest.js:1:564
```

I think the solution should be adding hash for manifest.js file too. 

Any idea? 

Thanks a lot.

**Comment by rstoenescu** [comment]
Can you provide more information pls? What starter kit are you using? The v0.14 or v0.15?

**Comment by lei-cao** [comment]
hi @rstoenescu 
Thank you for the prompt reply

I am using 
 Quasar CLI v0.6.5
and QUasar v0.14.7

This is the `quasar build` generated, manifest, vendor, app js doesn't have hash after it.
![image](https://user-images.githubusercontent.com/136104/35619499-358b9aa0-06b9-11e8-923c-cb9253f529cb.png)

Not sure if this should be done by webpack somehow. Buy anyway I am getting errors after every release because the those js are still loading from browser cache.

**Comment by rstoenescu** [comment]
Will handle this for v0.15. Thanks for reporting.

**Comment by rstoenescu** [comment]
Will be available starting with CLI 0.15.0-beta.41. Thanks for reporting!

**Comment by rstoenescu** [comment]
If you don't intend to spend some time upgrading to Quasar v0.15 right now, you can take a look at the commit above and make similar changes to your /build folder for v0.14.

**Comment by wa05** [comment]
Hi, I'm having the "cache problem" using Quasar v0.17, my app is in http://www.rosganet.com ... 

In the docs we can find  **Use a webpack manifest (runtime) file to avoid cache bust on vendor chunk changing hash on each build.** .. this manifest file is that precache-manifest.f2b81ffaffa45fb06919945db7ad80f7.js ? 

- We have to clean the site data from application tab in the console to verify the changes after every build...

- We already set this on quasar.conf.js
webpackManifest: true

Is there some "server way" to fix this ?
