### ISSUE TITLE
How to downgrade quasar-cli to the pervious version?

### ISSUE THREAD

**Issue by JosephMendez** [quasarframework/quasar-cli#60]
Accidentally upgraded my quasar-cli to the latest version, i want to restore to the previous version.

**Comment by rstoenescu** [comment]
Hi,

Please use Gitter or forum for questions.
To answer your question, you can check the Github releases link:

<img width="1001" alt="releases" src="https://user-images.githubusercontent.com/4665641/36475682-15430c5a-1704-11e8-8b52-716bc7b841f5.png">

```
$npm install -g quasar-cli@0.6.5
```
