### ISSUE TITLE
auto generated mains.js

### ISSUE THREAD

**Issue by mchikhaoui** [quasarframework/quasar-cli#61]
Hi Guys, 
Thanks for the greate work tha you made !
I think that autogenerated main.js is not always a good idea because sometimes we need to make business logic in.

**Comment by rstoenescu** [comment]
Hi. Thx. That's where App Plugins come into place. http://quasar-framework.org/guide/app-plugins.html

**Comment by mchikhaoui** [comment]
Plugins can't stop application starting
```
promise().then(resp => new Vue ....).catch(err => redirect ....)
```
as well sometime we need to use Instance Lifecycle Hooks ...
Anyway, that will be good if we have choice to use or not plugins instead of main.js.

Thanks

**Comment by rstoenescu** [comment]
You got `app` param in the export of a plugin. That's the root Vue component. You can use lifecycle hooks there. Also, not doing anything while the promise is resolved is bad UI.

**Comment by rstoenescu** [comment]
You got `app` param in the export of a plugin. That's the root Vue component. You can use lifecycle hooks there. Also, not doing anything while the promise is resolved is bad UI.

**Comment by trenoncourt** [comment]
Hi,
For my use, I need to redirect the user to another site (with msal). I do not want the user to see the site if he is not authenticated. It is possible to hook the created event with app but not to stop it (I think). This may cause the user to see the page briefly.

I can use a hack like that, but I don't think it's the best practice:
```htlm
<div id="q-app" v-if="loaded">
    <router-view />
  </div>
```

**Comment by rstoenescu** [comment]
Did you considered configuring the webserver to auto-redirect if user is not authenticated?

**Comment by trenoncourt** [comment]
For my use it is msal which handle that ([https://github.com/AzureAD/microsoft-authentication-library-for-js](https://github.com/AzureAD/microsoft-authentication-library-for-js)) :/

**Comment by mchikhaoui** [comment]
There is many other cases than authentication where we need to have full control of application entry point.
For me the best solution is to have a choice always.

Thanks

**Comment by rstoenescu** [comment]
There's going to be a special "boot" plugin in 0.15.6 where can you can make decisions whether to call `new Vue(app)` or not.

**Comment by trenoncourt** [comment]
Thanks for that, it will help me à lot :heart_eyes:

**Comment by rstoenescu** [comment]
Available through Quasar CLI v0.15.7

**Comment by mchikhaoui** [comment]
@rstoenescu Thanks for that, good decision;)

**Comment by rstoenescu** [comment]
I actually hate it. I can almost see that boot plugin being misused...

**Comment by rstoenescu** [comment]
I hope people understand this is not a replacement for main.js and read the docs on it carefully.
