### ISSUE TITLE
Better documentation of analize prop

### ISSUE THREAD

**Issue by danielo515** [quasarframework/quasar-cli#65]
Here is the current documentation of the analize property on the section about configuring quasar.conf build section:

analyze | Boolean | Show analysis of build bundle with webpack-bundle-analyzer.
-- | -- | --

Looking at the actual webpack code we can see that this is not completely accurate:

```js
    if (cfg.build.analyze) {
      const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin
      webpackConfig.plugins.push(
        new BundleAnalyzerPlugin(Object.assign({}, cfg.build.analyze))
      )
    }
```

It is even better ! You can provide an object that will be used as options for BundleAnalyzerPlugin. This is a very handy feature that deserves more attention.

I also noted that this only happens on production mode, which is not documented neither.
By the way, is there any way to check mode while extending the webpack config from quasar config ? Can I just check the `cfg.ctx.dev` on the extendWebpack function ?

Regards

**Comment by rstoenescu** [comment]
@danielo515 added that to docs. Will be available in next docs update.
Also, if you take a look, quasar.conf.js exports a function which takes a parameter (ctx).. Use that. http://quasar-framework.org/guide/app-quasar.conf.js.html
