### ISSUE TITLE
Migrate to Webpack 4

### ISSUE THREAD

**Issue by jpgilchrist** [quasarframework/quasar-cli#67]
I don't see it in any milestone or existing issue yet, so I figured I'd put it on your radar. It's supposed to be a lot faster 60 - 98% faster, in fact.

**Comment by rstoenescu** [comment]
It doesn't have to be on any milestone. Upgrading packages as they are available is always on my todo.
BUT, upgrade will occur when all the plugins are compatible with Webpack 4. It's just been released, so let's wait until things settle. Thanks.
