### ISSUE TITLE
[SUGGESTION] - URL format for 'hash' mode

### ISSUE THREAD

**Issue by adamkpurdy** [quasarframework/quasar-cli#71]
During development I noticed that 'vueRouterMode: hash' was causing the formatting of the url to be localhost:'portnumber'/index.html#/. 

This lead me to set my htmlFilename to and empty string. 

When I went to build my app I received and error due to setting this to an empty string. After discussing this issue with @rstoenescu he pointed out that I needed to remove that. I brought up the issue about the formatting URL issue, and it was noted that this was how vue-router handled the routing, but after I went back to my old quasar app, as well as looking at the basic Vue app using vue-router in hash mode, the format was still:  localhost:'portnumber'/#/ 

I went and tested my hypothesis and  edited the second half of the ternary operator to '#/' and removed the  'cfg.build.htmlFilename', so: localhost:'portnumber'/#/

So I did some digging in the cli and noticed at line 350 in quasar-config.js:

```
cfg.build.APP_URL = `http${cfg.devServer.https ? 's' : ''}://${host}:${cfg.devServer.port}/${cfg.build.vueRouterMode === 'hash' ? cfg.build.htmlFilename : ''}`
```

With that I did a quick experiment, and changed the file to:

```
cfg.build.APP_URL = `http${cfg.devServer.https ? 's' : ''}://${host}:${cfg.devServer.port}/${cfg.build.vueRouterMode === 'hash' ? '#/' : ''}`
```

Dev worked as I hoped, as did the build. Tested on http-server and the same format worked.

Can I make a minor request for a future release, or will this cause bigger issues that I'm not aware of?

Thanks!

**Comment by rstoenescu** [comment]
Hi,

1. Your change would break Cordova and Electron apps.
2. This URL has meaning only for the development server. It's NOT something that affects the production version in any way. **So why would you care about it?**
  2.a. You can however use vue-router history mode for development and return to hash mode for production if you want this badly, but I don't see the reason:
   ```js
   // quasar.conf.js
   build: {
     vueRouterMode: ctx.dev ? 'history' : 'hash'
  ```
  2.b What the browser cares about is changing that hash in the current URL. So if you start your browser session with /index.html it will add hash to that. If you start it with / it will fetch index.html anyway, but hash will be added to current URL, which has no mention of index.html, so it will basically be "/#/....".

**Comment by adamkpurdy** [comment]
🤦Oh man, thanks for explaining that. I automatically assumed that would be the case in production as well. Sorry for wasting your time on this.
