### ISSUE TITLE
template missing?

### ISSUE THREAD

**Issue by burningTyger** [quasarframework/quasar-cli#72]
### Software version

OS: Arch Linux
Node: 9.7.1
NPM: 5.7.1
Any other software related to your bug:

### What did you get as the error?
    $ quasar new page Profile Posts
     ✖ Template "page.vue" does not exists.
### What were you expecting?
     app:new Generated page: src/pages/Profile.vue +0ms
     app:new Make sure to reference it in src/router/routes.js + 2ms
### What steps did you take, to get the error?
In my app dir that I created. quasar dev works fine, everything else ok too.

**Comment by rstoenescu** [comment]
I just checked it... works:

```bash
00:14 $ quasar new page Profile Posts
 app:new Generated page: src/pages/Profile.vue +0ms
 app:new Make sure to reference it in src/router/routes.js +4ms

 app:new Generated page: src/pages/Posts.vue +0ms
 app:new Make sure to reference it in src/router/routes.js +1ms
```

**Comment by rstoenescu** [comment]
Please type "$ quasar info" and report back. I think you are not using the correct CLI version.

**Comment by burningTyger** [comment]
I think I updated and somehow reverted versions after successfully starting a .15 project. You were right.
