### ISSUE TITLE
`quasar dev` fails with older project, `npm run dev` OK

### ISSUE THREAD

**Issue by valeriancure** [quasarframework/quasar-cli#73]
### Software version

OS: win 10 64b
Node: v8.9.4 
NPM: 5.6.0
Any other software related to your bug:
quasar --version
0.15.5
### What did you get as the error?
On older project ("quasar-framework": "^0.14.4"), `quasar dev` does nothing. Process uses 10-12% of CPU, nothing happens, no console output.

But `npm run dev` runs smoothly

![image](https://user-images.githubusercontent.com/30051721/36960774-c81c6f4a-2048-11e8-8a4e-35ddeaeb6650.png)

**Comment by BenoitRanque** [comment]
The new Quasar-CLI is not compatible with older quasar versions. See [Docs](http://quasar-framework.org/guide/quasar-upgrade-guide.html#Quasar-CLI-and-Pre-0-15-Apps) for instructions on running older quasar versions for older projects

**Comment by valeriancure** [comment]
Thanks, I had missed that section of the docs.
