### ISSUE TITLE
Unexpected behavior on quasar init

### ISSUE THREAD

**Issue by BenoitRanque** [quasarframework/quasar-cli#74]
OS: Win 10
Node: 8.9
NPM: 5.5.1
Any other software related to your bug:
Quasar-Cli 0.15.7
### What did you get as the error?

Unexpected behavior when calling `quasar init` without project name parameter.

Quasar inits project "undefined" in folder "undefined"

### What were you expecting?

Init Quasar project in current folder, choose name in interactive cli

**Comment by rstoenescu** [comment]
Fix will be available in 0.15.8.
