### ISSUE TITLE
Cordova mode init broken

### ISSUE THREAD

**Issue by brindosch** [quasarframework/quasar-cli#77]
### Software version

OS: Ubuntu 16.04 64it
Node: 8.9.4
NPM: 5.6.0
Quasar-cli: 0.15.7

Any other software related to your bug:
-
### What did you get as the error?
src-cordova folder is missing
### What were you expecting?
Working codova init
### What steps did you take, to get the error?
While using `quasar mode -a cordova` inside project folder no 'src-cordova' folder is created
The project folder itself has been created with SPA template before
I followed your great tutorial [Tut](http://quasar-framework.org/guide/cordova-preparation.htm)

The output of quasar-cli looks good. I wonder where it trys to create the folder
```
project-folder$ quasar mode -a cordova
 app:mode-cordova Creating Cordova source folder... +0ms
 app:spawn [sync] Running "cordova create src-cordova (org.cordova.xxx.app) xxx" +2ms

(node:30665) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): CordovaError: App id contains a reserved word, or is not a valid identifier.
(node:30665) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 app:mode-cordova Cordova support was installed +377ms
 app:mode-cordova App name was taken from package.json: "xxx" +0ms

 app:mode-cordova If you want a different App name then remove Cordova support, edit productName field from package.json then add Cordova support again. +0ms

 app:mode-cordova Please manually add Cordova platforms using Cordova CLI from the newly created "src-cordova" folder. +0ms

```
Thank you for every hint. If you need more info just ask.

**Comment by rlam3** [comment]
@brindosch were you able to find a solution? I simply pushed to a repo and pulled it back from my repo on a seperate machine and got this error.... was wondering if you had any workarounds. thanks!

**Comment by nsh-core** [comment]
getting this aswell any one got a solution? seems like if you re-run quasar mode -a cordova it says it is already enabled?

**Comment by rstoenescu** [comment]
"CordovaError: App id contains a reserved word, or is not a valid identifier" --> use a valid identifier! :)
