### ISSUE TITLE
Vue-cli v3.0.0 & Quasar-Cli v0.15.7 - Request for harmony

### ISSUE THREAD

**Issue by paritosh149** [quasarframework/quasar-cli#78]
Vue-cli v3.0.0 is in beta currently. It has a Manual Mode to select various features of the project such shown below
```
? Please pick a preset: Manually select features
? Check the features needed for your project: TS, PWA, Router, Vuex, CSS Pre-processors, Linter, Unit, E2E
? Use class-style component syntax? Yes
? Use Babel alongside TypeScript for auto-detected polyfills? Yes
? Pick a CSS pre-processor (PostCSS, Autoprefixer and CSS Modules are supported by default): SCSS/SASS
? Pick a linter / formatter config: TSLint
? Pick additional lint features: Lint on save
? Pick a unit testing solution: Mocha
? Pick a E2E testing solution: Cypress
? Where do you prefer placing config for Babel, PostCSS, ESLint, etc.? In dedicated config files
? Save this as a preset for future projects? (Y/n)
```
This gives a flexible way to initialize my project.

However, Quasar CLI v0.15.7 still calls upon legacy command `vue init quasar-starter-kit`  

Can Quasar CLI allow Manual feature selection similar to Vue CLI?

**Comment by rstoenescu** [comment]
It does ask you how you want your project configured. Are you looking for something specific instead?
Quasar CLI !== Vue CLI. It works on totally different principles.

If you are looking for the official Vue CLI 3 plugin, here it is: https://github.com/quasarframework/vue-cli-plugin-quasar
Note that the premium way of dealing with Quasar is through Quasar CLI.

**Comment by paritosh149** [comment]
Thanks @rstoenescu , this helps my situation. Steps are given in issue #64.
