### ISSUE TITLE
Use yarn everywhere (if selected)

### ISSUE THREAD

**Issue by nothingismagick** [quasarframework/quasar-cli#84]
For example, in `mode-electron.js` we are still assuming that the user has npm installed:

```
    spawn.sync(
      'npm',
      ['install', '--save-dev', '--save-exact'].concat(Object.keys(electronDeps).map(dep => {
        return `${dep}@${electronDeps[dep]}`
      })),
      appPaths.appDir,
      () => warn('Failed to install Electron dependencies')
    )
```
Solution: When the user chooses a build command, this should be respected later. Therefore I would recommend placing this in the getQuasarConfigCtx() function in `quasar-config.js` - and checking against that value before updating the user's `package.json`...

**Comment by nothingismagick** [comment]
This issue is treated in this pull-request: https://github.com/quasarframework/quasar-cli/pull/76/commits/9ba8ae293b90b5edbd4682751601d8ddc38e647f but the requestor has not provided a mechanism for switching.

**Comment by rstoenescu** [comment]
Available in next CLI version with Webpack 4.
