### ISSUE TITLE
Login form

### ISSUE THREAD

**Issue by george-kar** [quasarframework/quasar-cli#90]
Is there any ready made login form layout? Of course I can create a new one from scratch but if there's anything already it will save me time.

Example: https://codesandbox.io/s/github/vuematerial/examples/tree/master/examples/login

**Comment by nothingismagick** [comment]
This question seems more like a component and would be more appropriate over at https://github.com/quasarframework/quasar - this repo is for the quasar-cli - which is a very different scope.

**Comment by george-kar** [comment]
yes my mistake.
