### ISSUE TITLE
High CPU usage while running quasar dev

### ISSUE THREAD

**Issue by monoc44** [quasarframework/quasar-cli#97]
Hi there,

__Quasar-cli__: 0.15.9
__OS__: MacOS Sierra (10.12.6 (16G29))
__Node__: 8.9.4
__NPM__: 5.6.0

Running `quasar-dev` for a few minutes, with WDS on, brings CPU to high temperature. I have no choice but stopping the server to let fans cooling off.

Problems seems to be related to the `usernoted` process on Mac OSX.

Narrowing down the problem leads to:
`/usr/local/lib/node_modules/quasar-cli/node_modules/node-notifier/vendor/terminal-notifier.app/Contents/MacOS/terminal-notifier`

-> Got a few processes running simultaneously on my machine, not sure if this is expected.

Switching off `terminal-notifier` in Notifications (system preferences) doesn’t help either.
Any idea?

Many thanks
(… and bravo for Quasar, it really rocks!)

**Comment by nothingismagick** [comment]
I can confirm this issue is happening, also on MacOS Sierra 10.12.6 - my not so subtle workaround is to 

`$ pkill usernoted`

Still looking for a solution.

**Comment by nothingismagick** [comment]
And for me, depending on what else is happening, the entire computer freezes... Usually happens when a build fails. The obvious solution is to never try and compile anything that is broken... LOL

**Comment by nothingismagick** [comment]
So this is the source in our codebase - I am a little worried about `undefined` - I think `false` would be better.

https://github.com/quasarframework/quasar-cli/blob/3726f84421da7b62ca6f2c41fecd23d500018393/lib/helpers/notifier.js#L18

**Comment by nothingismagick** [comment]
According to the docs at node-notifier:
`wait: false, // Wait for User Action against Notification or times out. Same as timeout = 5 seconds`
So it might actually be more clever to do:
`wait: hasClick ? true : false,`

**Comment by nothingismagick** [comment]
@monoc44 - you might want to look into the following setting in your quasar.conf.js file’s
```
module exports 
  build
    useNotifier: false
```

**Comment by monoc44** [comment]
Perfect, I will give it a try.
You are right, it seems happening when build is in error.

**Comment by rstoenescu** [comment]
Fix will be available in 0.15.15.

**Comment by mstaack** [comment]
awesome!

**Comment by monoc44** [comment]
I confirm that the workaround provided by @nothingismagick works perfectly. I will test the fix and get back to you if it doesn’t work. Thanks for your help, appreciate it.

**Comment by rstoenescu** [comment]
Thanks for reporting this issue. I am also using a Mac, with notifier turned on, but haven't noticed it. Regardless, fix will be embedded in next CLI version scheduled for release in 1-2 days after I get back from my short vacation, so around end of next week.
