### ISSUE TITLE
[PROPOSAL] Add WebPack Dashboard and bundlesize to the CLI

### ISSUE THREAD

**Issue by bloodf** [quasarframework/quasar-cli#98]
For the CLI to be improved we can add two plugins to the WebPack.

### Dashboard
- https://github.com/FormidableLabs/webpack-dashboard
It's a fully featured dashboard for terminal that reads all the webpack stdout and make a great looks with infos for the development of the system.

### BundleSize
- https://github.com/siddharthkp/bundlesize
A plugin that was featured at Chrome Dev Summit and it's all about making the web faster. It check the max file size for each chunk and .JS so we have smaller files that will be generated and faster parallel loading.

**Comment by nothingismagick** [comment]
Both are nice, would be great to have them as modes

**Comment by nothingismagick** [comment]
I am voting to close this, because according to the project's package.json, its dev-dependency is:
https://github.com/FormidableLabs/webpack-dashboard/blob/master/package.json#L62

```
    "webpack": "^2.3.2"
```
@rstoenescu - what do you think?
