### ISSUE TITLE
[PROPOSAL] Add support for vue-stash

### ISSUE THREAD

**Issue by danikane** [quasarframework/quasar-cli#99]
Hi Razvan, many thanks AGAIN for a well-polished framework!
I've been using [vue-stash](https://github.com/cklmercer/vue-stash) for quite some time and I've grown really fond of it. :)
Currently only Vuex is supported.
I made some changes to support the use of vue-stash and it's working fine for me.
If anyone else would like to use the workaround here's the link to the thread:
http://forum.quasar-framework.org/topic/2029/state-management-other-than-vuex

I'd be happy to do a PR if this feature get enough supporters.

**Comment by rstoenescu** [comment]
Hi,

Copy pasting my answer from the forum link here, for completeness:

This can be done entirely using the app plugin system. Notice you can do injections to app (export default ({ ...., >>> app <<<, ...})) and you can also re-export any other things you need, like the store, if you really need it (const store = { ..... } then export { store, ...any_other_named_export }).

Also, worth mentioning that app is ‘src/App.vue’, so if you feel uncomfortable to do the data injection in an app plugin, you can directly do that in src/App.vue.

There is no need to touch entry.js, nor should you.

**Comment by danikane** [comment]
Thank you, I did it as you suggested and using the plugin system. It's great! :)
